apiVersion: v1
kind: ServiceAccount
metadata:
  name: exchangeapp
  namespace: exchangeapp
  labels:
    app.kubernetes.io/name: exchangeapp
automountServiceAccountToken: false   # 不自动挂载 API token，最小权限原则
